export const books = [
	{
		title: 'The Wise Man\'s Fear',
		author: 'Patrick Rothfuss',
		genre: 'Fiction',
		year: 2012,
		date: 2023,
		difficulty: '★',
		rating: '★★★★★',
		comments: `The second book went faster than the first! I basically read for two days straight. It took five years between the first and the second book but this one has been out for 11 years and no third in site. The author has recently commented that the third book is going more slowly than he would like and the most recent specualtion in 2024. In the meantime he has written another book as a kind of spin off about one of the more curious characters in the story and I think I will get that next!`,
		coverPic: './images/bookImages/thewisemansfear.jpg',
		ammazonLink:
			'https://www.amazon.ca/Wise-Mans-Fear-Patrick-Rothfuss/dp/0756407125/ref=pd_lutyp_d_ci_mcx_mr_typ_d_sccl_2_2/131-6376192-8975257?pd_rd_w=naWLJ&content-id=amzn1.sym.14b1870b-aff2-4381-bdd6-2c248259ec0d&pf_rd_p=14b1870b-aff2-4381-bdd6-2c248259ec0d&pf_rd_r=3FXSSXWD4CXEGK3G5ZA7&pd_rd_wg=zZlMp&pd_rd_r=4b00217d-8c40-4c5c-9112-1cc5d39fbc4e&pd_rd_i=0756407125&psc=1',
	},
	{
		title: 'The Name of the Wind',
		author: 'Patrick Rothfuss',
		genre: 'Fiction',
		year: 2007,
		date: 2023,
		difficulty: '★',
		rating: '★★★★★',
		comments: `I needed a good fiction distraction this week and this author has been on my list for a while now. It did NOT disappoint! Magic, sword fights, good and evil.. What more do you need!? I hesitate to talk too much about fiction for fear of giving away the story but I will say I was pulled in within the first couple chapters and finished it in three days. The character building is second to none and I felt the mood of the scenes thoroughly. I am eager to read the next one and a little upset that the series is not finished...`,
		coverPic: './images/bookImages/thenameofthewind.jpg',
		ammazonLink:
			'https://www.amazon.ca/Name-Wind-Kingkiller-Chronicle-Day/dp/0756404746/ref=tmm_mmp_swatch_0?_encoding=UTF8&qid=1685021699&sr=8-4',
	},
	{
		title: 'The Self Illusion',
		author: 'Bruce Hood',
		genre: 'Science - Psychology',
		year: 2012,
		date: 2023,
		difficulty: '★★★★',
		rating: '★★★★★',
		comments: `You may not be what or who you think you are! This was a thought provoking read on the topic of identity and what that is. The author argues that identity is basically an illusion created by our brains to give us a means to experience and interact with the world around us. It gets really interesting ( read as creepy ) when he starts to talk about how that would affect ideas like free will and personal responsiility.`,
		coverPic: './images/bookImages/theselfillusion.jpg',
		ammazonLink:
			'https://www.amazon.ca/Self-Illusion-Bruce-Hood/dp/144340523X/ref=sr_1_1?keywords=the+self+illusion&qid=1685014288&sprefix=the+self+ill%2Caps%2C78&sr=8-1',
	},
	{
		title: 'Crypto',
		author: 'Stephen Levy',
		genre: 'Science - Social Commentary',
		year: 2001,
		date: 2023,
		difficulty: '★★★★★',
		rating: '★★★★★',
		comments: `I started this book back in October and just picked it back up a few weeks ago. Many would assume the book is about cryptocurrency, but it is actually about the history and development of cryptography. Cryptography has become ubiquitous in modern society, being used in everything from online banking to digital ID verification. At times it can be very technical and at times fairly dry reading. A lot of time is spent contrasting and balancing the need for security VS the need for privacy. I would not recommend it for casual reading but if you have any interest in this type of thing, what a fantastic book!`,
		coverPic: './images/bookImages/crypto.jpg',
		ammazonLink:
			'https://www.amazon.ca/Crypto-Rebels-Government-Saving-Privacy-Digital/dp/0140244328/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1683296595&sr=8-2',
	},
	{
		title: 'Fooled by Randomness',
		author: 'Nicholas Taleb',
		genre: 'Science',
		year: 2004,
		date: 2023,
		difficulty: '★★★',
		rating: '★★★★★',
		comments: `I was not sure how to categorize this. I put it in Science but could easily be called a self help book or even social commentary. The author argues that people tend to underestimate the role of chance and randomness in life, particularly in the fields of finance and business. He also stresses the importance of being skeptical of experts who claim to have all the answers, as they may not fully understand the role of randomness in their fields.`,
		coverPic: './images/bookImages/fooledbyrandomness.jpg',
		ammazonLink:
			'https://www.amazon.ca/Fooled-Randomness-Hidden-Chance-Markets/dp/1400067936/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1682603306&sr=8-1',
	},
	{
		title: 'Essentialism',
		author: 'Greg McKeown',
		genre: 'Self Help',
		year: 2014,
		date: 2023,
		difficulty: '★',
		rating: '★★★★★',
		comments: `Dealing with my recent burnout from stacking up too many expectations and spreading myself too thin, this book was extremely topical and helpful. The author provides some simple tools and strategies to help focus efforts on prioritzed goals, organize and simplify our routines, embrace the growth mindset and what I found to be most helpful prioritzing self-care. I think if I had read this book months earlier I would not have had to step away for so long. Highly recommend.`,
		coverPic: './images/bookImages/essentialism.jpg',
		ammazonLink:
			'https://www.amazon.ca/Essentialism-Disciplined-Pursuit-Greg-McKeown/dp/0804137404/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1682254384&sr=8-1',
	},
	{
		title: 'Think Like a Monk',
		author: 'Jay Shetty',
		genre: 'Self Help',
		year: 2020,
		date: 2023,
		difficulty: '★★',
		rating: '★★★★',
		comments: `Written by a former Monk and filled with very practical advice. The book is divided up into three parts that correspond to the different stages of monk training : Let Go, Grow, and Give. The first part is very calming, the second part is very motivational and well, I am still working on the third part which is living a life of service to others. Baby steps!
        `,
		coverPic: './images/bookImages/thinklikeamonk.jpg',
		ammazonLink:
			'https://www.amazon.ca/Think-Like-Monk-Export-Shetty/dp/1982149817/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1682253301&sr=8-1',
	},
	{
		title: 'Wilderness and the American Mind',
		author: 'Roderick Frazier Nash',
		genre: 'Social Commentary',
		year: 1967,
		date: 2023,
		difficulty: '★★★',
		rating: '★★★★★',
		comments: `I found the book to be very interesting. It gives a historical account of how our perspective of "wilderness" has evolved since colonizing North America. Our view on nature and how we should treat our environment has shifted along with the current cultural, economic and political conditions. Also of note that 55 years after being written the book is still reference material for many university environmental conservation programs.
        `,
		coverPic: './images/bookImages/wildernessandtheamericanmind.jpg',
		ammazonLink:
			'https://www.amazon.ca/Wilderness-American-Mind-WILDERNESS-Paperback/dp/B00QPVFUIA/ref=sr_1_5?crid=3RIC31TLK8EA3&keywords=wilderness+and+the+american+mind&qid=1682249850&sprefix=winderness+and+the+american+mind%2Caps%2C69&sr=8-5',
	},
	{
		title: 'Cobalt Red',
		author: 'Siddharth Kara',
		genre: 'Social Commentary',
		year: 2023,
		date: 2023,
		difficulty: '★★',
		rating: '★★★★★',
		comments: `Any device powered by a rechargeable lithium-ion battery requires cobalt for manufacture. Roughly 75% of the world's supply of cobalt comes from the Congo. The conditions under which some of the supply is obtained are appalling. Child labor economically forced slave labor, and inhumane working conditions are commonplace. Nobody wants to take responsibility for it, so we all bear some of the blame. Truly heart-wrenching to read and I feel guilty for being a part of the problem.`,
		coverPic: './images/bookImages/cobaltred.jpg',
		ammazonLink:
			'https://www.amazon.ca/Cobalt-Red-Blood-Congo-Powers/dp/1250284309/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1676481477&sr=8-1',
	},
	{
		title: 'The Secret',
		author: 'Rhonda Byrne',
		genre: 'Philosophy - Spirituality',
		year: 2006,
		date: 2023,
		difficulty: '★',
		rating: '★★★',
		comments: `Every year I ask for books for Christmas and this was one I received this year. The woman that gave it to me swears by it. While I am not sure that I believe we can cause things to physically manifest themselves in our lives by our thoughts alone, I do believe in the power of positive thought and visualization.`,
		coverPic: './images/bookImages/thesecret.jpg',
		ammazonLink:
			'https://www.amazon.ca/Secret-Rhonda-Byrne/dp/1582701709/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1676480268&sr=8-1',
	},
	{
		title: 'The Hunger',
		author: 'Alma Katsu',
		genre: 'Fiction',
		year: 2018,
		date: 2023,
		difficulty: '★',
		rating: '★★★★★',
		comments: `It was time to get a little fix of fiction in the mix! The Hunger takes place during a BRUTAL time in America's history.  Many people were opting to make a perilous journey from the East Coast to West and encountered all sorts of dangers. Once I started the book, I could not put it down. Chilling.`,
		coverPic: './images/bookImages/thehunger.jpg',
		ammazonLink:
			'https://www.amazon.ca/Hunger-Alma-Katsu/dp/0735212511/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1676477326&sr=8-1',
	},
	{
		title: 'What We Owe the Future',
		author: 'William MacAskill',
		genre: 'Philosophy - Social Commentary',
		year: 2022,
		date: 2023,
		difficulty: '★★★★',
		rating: '★★★★★',
		comments: `Not sure I agree with everything the author has to say but that's the point of reading for me. His research and fact checking effort was impressive. The book gave me lots to think about including a very cool idea he calls value lock in. If the author is right we are living in some very important and scary times indeed! Great book.`,
		coverPic: './images/bookImages/whatweowethefuture.jpg',
		ammazonLink:
			'https://www.amazon.ca/What-Owe-Future-William-MacAskill/dp/1541618629/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1674571151&sr=8-1',
	},
	{
		title: 'The PMA Effect',
		author: 'John Joseph',
		genre: 'Philosophy - Self Improvement',
		year: 2018,
		date: 2023,
		difficulty: '★',
		rating: '★★★★★',
		comments: `I have listened to this book several times since it came out. Given my current struggles with motivation and my habits I thought a good dose of straight talk from John Joseph was needed. This guys story is almost unbelievable and he definitely holds no bars when giving his opinion on what is or is not holding you back from your goals. One of my favorite books, period.`,
		coverPic: './images/bookImages/thepmaeffect.jpg',
		ammazonLink:
			'https://www.amazon.ca/The-PMA-Effect/dp/0998344745/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1674571576&sr=8-1',
	},
	{
		title: 'The Art of Stillness in a Noisy World',
		author: 'Magnus Fridh',
		genre: 'Health - Self Improvement',
		year: 2020,
		date: 2023,
		difficulty: '★',
		rating: '★★★★',
		comments: `There is no doubt that meditation provides numerous mental and physical health benefits with even small amounts of time. This is a great book for someone just starting to get into the habit. The author tells stories and describes real scenarios when he uses several easy techniques.`,
		coverPic: './images/bookImages/theartofstillnessinanoisyworld.jpg',
		ammazonLink:
			'https://www.amazon.ca/Art-Stillness-Noisy-World/dp/1784883697/ref=sr_1_1?crid=28HSBPX72D6K3&keywords=the+art+of+stillness+in+a+noisy+world&qid=1674570811&sprefix=the+art+of+stillne%2Caps%2C77&sr=8-1',
	},
	{
		title: 'Cosmic Queries',
		author: 'Neil deGrasse Tyson / James Trefil',
		genre: 'Science',
		year: 2021,
		date: 2023,
		difficulty: '★★★',
		rating: '★★★★',
		comments: `Very easy to read considering the subject matter. You will go from feeling very small to very large and get a good review of how we came to be and where things could be headed. Spoiler Alert - It all ends the same way!`,
		coverPic: './images/bookImages/cosmicqueries.jpg',
		ammazonLink:
			'https://www.amazon.ca/Cosmic-Queries-StarTalks-Guide-Where/dp/B08PW2N8R3/ref=sr_1_1?keywords=cosmic+queries&qid=1673360080&s=books&sprefix=cosmic+%2Cstripbooks%2C67&sr=1-1',
	},
	{
		title: '100 Philosophers',
		author: 'Lesley Levene',
		genre: 'Philosophy - History',
		year: 2021,
		date: 2023,
		difficulty: '★',
		rating: '★★★★',
		comments:
			'A great reference book if you are interested in reading about how people think we should think. It is ordered chronologically which shows us how certain types of thinking aligned with historical periods. I came away with a few new books to read.',
		coverPic: './images/bookImages/philosophers.jpg',
		ammazonLink:
			'https://www.amazon.ca/100-Philosophers-Wisdom-Worlds-Thinkers-ebook/dp/B099X94GTC/ref=sr_1_1?keywords=100+philosophers&qid=1673360425&s=books&sprefix=100+philosop%2Cstripbooks%2C77&sr=1-1',
	},
	{
		title: 'Ikigai',
		author: 'Hector Garcia / Francesc Miralles',
		genre: 'Science - Social Commentary',
		year: 2016,
		date: 2022,
		difficulty: '★',
		rating: '★★★★',
		comments:
			'Want to chase the rabit and live forever? Read about the longest living (and happiest?) people in the world. Super easy read and offers some easy to follow examples we can all take from.',
		coverPic: './images/bookImages/ikigai.png',
		ammazonLink:
			'https://www.amazon.ca/gp/product/0143130722/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1',
	},
	{
		title: 'Tao Te Ching',
		author: 'Lao-Tzu (Jonathan Star Translation)',
		genre: 'Philosophy - Religion',
		year: 2016,
		date: 2022,
		difficulty: '★★',
		rating: '★★★★',
		comments:
			'A book of poetry and one of the fundamental texts of Taoism. Like a lot of the Eastern religions and philosophies it will take many reads to get the most of this work. I like the overall message that we all need to chill a little more to enjoy life.',
		coverPic: './images/bookImages/taoteching.png',
		ammazonLink:
			'https://www.amazon.ca/gp/product/1585426180/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1',
	},

	{
		title: 'Weapons of Math Destruction',
		author: "Cathy O'Neil",
		genre: 'Science - Social Commentary',
		year: 2016,
		date: 2022,
		difficulty: '★★',
		rating: '★★★★',
		comments:
			'A good look at how big data and algorithms can and are having an impact on society. Lots of examples, some troubling. An easy read on a complex subject.',
		coverPic: './images/bookImages/weaponsofmathdestruction.jpg',
		ammazonLink:
			'https://www.amazon.ca/Weapons-Math-Destruction-Increases-Inequality/dp/B072Q1MLT5/ref=sr_1_1?crid=36G3NPTNGP1WH&keywords=weapons+of+math+destruction+audible&qid=1670187315&sprefix=weapons+of+math+destruction+audible%2Caps%2C76&sr=8-1',
	},
	{
		title: 'Beyond Order',
		author: 'Jordan B. Peterson',
		genre: 'Self Improvement',
		year: 2021,
		date: 2022,
		difficulty: '★★★',
		rating: '★★★★★',
		comments:
			"Regardless of what some people may think of his public opinions or politics it is hard to argue the correctness of the advice he gives in this book or it's predecesor. The overall message in the book is easy to grasp but I rated it a little higher for difficulty as it is full of references that require digestion.",
		coverPic: './images/bookImages/beyondorder.jpg',
		ammazonLink:
			'https://www.amazon.ca/Beyond-Order-More-Rules-Life/dp/0735278334/ref=sr_1_1?crid=2AS70JTPLCGOP&keywords=beyond+order+hardcover&qid=1670185280&sprefix=beyond+order+hardcover%2Caps%2C71&sr=8-1',
	},
	{
		title: 'Apocalypse Delayed',
		author: 'M. James Penton',
		genre: 'Religion - History',
		year: 1985,
		date: 2022,
		difficulty: '★★★★',
		rating: '★★★★',
		comments:
			'A thorough and sometimes illuminating look at the environment around the forming and evolution of the Jehovah\'s Witnesses. I gave this book a high difficulty rating due to the "dryness" of the reading.',
		coverPic: './images/bookImages/book3.jpg',
		ammazonLink:
			'https://www.amazon.ca/Apocalypse-Delayed-Story-Jehovahs-Witnesses/dp/1442616059/ref=sr_1_1?keywords=apocalypse+delayed+3rd+edition&qid=1670005220&qu=eyJxc2MiOiIwLjg0IiwicXNhIjoiMC4wMCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=apocalypse+del%2Caps%2C72&sr=8-1',
	},
	{
		title: 'Tools Of Titans',
		author: 'Tim Ferriss',
		genre: 'Self Improvement',
		year: 2017,
		date: 2022,
		difficulty: '★',
		rating: '★★★★★',
		comments:
			'This book is actually an ongoing read. I have read it through once and now use it as a resource when I am looking for new things to try or read. An amazing compendium of snapshots into the things and information some of the most successful people in the world have found valuable. And I am a HUGE Tim Ferriss fan. Check out his podcasts!',
		coverPic: './images/bookImages/toolsoftitans.jpg',
		ammazonLink:
			'https://www.amazon.ca/Tools-Titans-Billionaires-World-Class-Performers/dp/1328683788/ref=sr_1_1?crid=31L4CGNGQ9FAV&keywords=tools+of+titans+hardcover&qid=1670184469&s=audible&sprefix=tools+of+titans+hardcover%2Caudible%2C74&sr=1-1-catcorr',
	},
	{
		title: 'Calling Bullshit',
		author: 'Carl T. Bergstrom',
		genre: 'Science - Social Commentary',
		year: 2020,
		date: 2022,
		difficulty: '★★',
		rating: '★★★★★',
		comments:
			'Super relevant subject matter considering the amount of information that we have at our fingertips in this era. The book promotes a healthy mistrust and skepticism of any information and especially when backed by statistics and studies. An easy read that uses simple examples to make you aware how easily we can be misled.',
		coverPic: './images/bookImages/callingbullshit.jpg',
		ammazonLink:
			'https://www.amazon.ca/Calling-Bullshit-Skepticism-Data-Driven-World/dp/B0876GK84C/ref=sr_1_1?crid=F0E6ERD5T9QD&keywords=calling+bullshit+audible&qid=1670183005&sprefix=calling+bullshit+audible%2Caps%2C74&sr=8-1',
	},
	{
		title: 'The Four Agreements',
		author: 'Don Miguel Ruiz',
		genre: 'Philosophy - Self Improvement',
		year: 1997,
		date: 2022,
		difficulty: '★',
		rating: '★★★★★',
		comments:
			'I have read this book a few times over the years. It begins by talking about how we are all socially conditioned by our families and society and the effect that has on us. It then suggests four cornerstone philosophies to start with to unwind some of the less wanted residuals from that.',
		coverPic: './images/bookImages/thefouragreements.jpg',
		ammazonLink:
			'https://www.amazon.ca/Four-Agreements-Practical-Personal-Freedom/dp/1878424319/ref=sr_1_1?crid=4Y50PPW4DRG6&keywords=the+four+agreements+paperback&qid=1670182184&sprefix=the+four+agreements+paperback%2Caps%2C69&sr=8-1',
	},
	{
		title: 'The Compound Effect',
		author: 'Darren Hardy',
		genre: 'Psychology - Self Improvement',
		year: 2010,
		date: 2022,
		difficulty: '★',
		rating: '★★★★★',
		comments:
			'I read this book at least once a year. I read it again when I started this experiment to remind myself how powerful consistent effort can be. A must read for anyone that feels intimidated by how far away their goals seem.',
		coverPic: './images/bookImages/thecompoundeffect.jpg',
		ammazonLink:
			'https://www.amazon.ca/Compound-Effect-Darren-Hardy/dp/9390924634/ref=sr_1_1?crid=2YOY4S8QU45P3&keywords=the+compound+effect+paperback&qid=1670181553&s=audible&sprefix=the+compound+effect+paperback%2Caudible%2C76&sr=1-1-catcorr',
	},
	{
		title: 'Atomic Habits',
		author: 'James Clear',
		genre: 'Psychology - Self Improvement',
		year: 2012,
		date: 2022,
		difficulty: '★',
		rating: '★★★★★',
		comments:
			"This is an annual read and I read it again when I started this experiment. Filled with super practical advice and easy to implement practices. In my opinion it is the gold standard for a place to start when you are looking to reform old habits or make brand new one's stick.",
		coverPic: './images/bookImages/atomichabits.png',
		ammazonLink:
			'https://www.amazon.ca/Atomic-Habits-James-Clear/dp/1847941834/ref=sr_1_1?gclid=Cj0KCQiAyracBhDoARIsACGFcS5uVkM8HHM6vuEtZ3ip208IqB3xFu4YloFMDX51RVHALvm8zGJh8coaAls7EALw_wcB&hvadid=600249105493&hvdev=c&hvlocphy=9000654&hvnetw=g&hvqmt=e&hvrand=9528657224061903935&hvtargid=kwd-988725570918&hydadcr=21681_13372336&keywords=atomic+habits+book+paperback&qid=1670282953&sr=8-1',
	},
];

export default books;
